name: Build/Deploy

# on: release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: /
    steps:
    - name: Install deps
      run: sudo apt-get install -y ruby-full rubygems bundler jekyll
    - name: Build site
      run: sudo jekyll build
