name: Build/Deploy

# on: release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build site (bundler)
      run: bundle exec jekyll build
