name: Build/Deploy

# on: release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: /
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt-get install -y rubygems bundler jekyll
    - name: Build site (bundler)
      run: bundle exec jekyll build
