name: Build/Deploy

# on: release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install deps (bundler)
      run: sudo apt-get install -y gcc make ruby-full rubygems bundler jekyll
    - name: Build site
      run: bundle exec jekyll serve
