name: Build/Deploy

# on: release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install deps (bundler)
      run: apt install bundler
    - name: Build site
      run: bundle exec jekyll serve
